name: fckng_portfolio
version: 0.0.1
description: Fckng portfolio.
author: Honza Bittner
homepage: http://honzabittner.cz

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  intl: '^0.15.2'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
